# Generated by Django 5.0.14 on 2025-10-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubeaccount",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="youtubeaccount",
            name="token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
