# Generated by Django 5.0.14 on 2025-10-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0002_alter_mediafile_options_mediafile_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="is_normalized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="normalized_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/normalized/"
            ),
        ),
    ]
