# Generated by Django 5.0.14 on 2025-10-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0003_mediafile_is_normalized_mediafile_normalized_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediafile",
            name="is_normalized",
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="normalized_file",
        ),
    ]
