# Generated by Django 5.0.14 on 2025-11-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="storage_limit",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
