# Generated by Django 5.0.14 on 2025-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediafile",
            options={
                "ordering": ["sequence", "created_at"],
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
            },
        ),
        migrations.AddField(
            model_name="mediafile",
            name="sequence",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
