# Generated by Django 5.0.14 on 2025-11-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0004_remove_mediafile_is_normalized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/stream_thumbnails/"
            ),
        ),
    ]
